#!/bin/sh

userresources=$HOME/.config/x11/Xresources
usermodmap=$HOME/.config/x11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if command -v dbus-launch >/dev/null && test -z "${DBUS_SESSION_BUS_ADDRESS}"; then
       eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

xwallpaper --daemon --zoom "$HOME/.local/share/wallpapers/wall_secondary.png" &
runsvdir ~/.config/runit/runsvdir &
blueman-applet &
devmon &
clipmenud &
dwmblocks &
exec dwm
