#!/bin/sh
while read file
do
    case "$1" in
    "w") xwallpaper --zoom "$file" & ;;
	"r") convert -rotate 90 "$file" "$file" ;;
	"R") convert -rotate -90 "$file" "$file" ;;
	"f") convert -flop "$file" "$file" ;;
	"y") copy-file "$file" && notify-send "$file copied to clipboard" & ;;
	"d") [ "$(printf "Yes\\nNo" | dmenu -f -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
	"i") notify-send "File information" "$(mediainfo "$file")" ;;
        esac
done
